# Generated by Django 3.1.6 on 2021-02-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210215_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountPercentage',
            field=models.IntegerField(null=True),
        ),
    ]
