# Generated by Django 3.1.6 on 2021-02-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210215_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discountPercentage',
        ),
    ]
