# Generated by Django 3.1.6 on 2021-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexe',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme')], max_length=10, null=True),
        ),
    ]
