# Generated by Django 3.1.6 on 2021-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210221_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, default='person.png', upload_to='images/users/'),
        ),
    ]
