# Generated by Django 3.1.6 on 2021-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
